// The total price displayed includes all applicable government taxes.You are required to pay the entire amount prior to the confirmation of your booking.There will be no refund for 'no-shows' or any partially unused flights.To avail of infant fares, an infant must be under 24 months throughout the entire itinerary you are booking. This includesboth onward and return journeys. If the infant is 24 months or above on the return journey, you'll need to make aseparate booking using a child fare.Infants must be accompanied by an adult at least 18 years of age

// Check in:
//  As per the airline rules, the standard check-in time begins 2 hours before departure.For Air India flights the check-in time is 3 hours before departure and is at the International Terminal.Infants must have valid proof-of-age documents showing that the infant is under two years old.
// Amendments:
// Cleartrip can assist you with amendments to most bookings. In some cases, though, you'll need to contact theairline directly.Every booking made on Cleartrip is subject to amendment charges levied by the airline, which may vary by flightand booking class.If you amend your booking, you will be charged the difference in fare, if any, applicable when the amendment ismade. However if the new fare is lower than the Original fare, difference in the amount will not be refunded,butthe rebooking charges as applicable will be collected.In addition to the airline's amendment charges, Cleartrip charges an amendment handling fee of Rs 300 per passenger per segment.We'll collect these charges from you when we make the changes to your travel plans. We'll also collect thedifference in fare, if any, applicable when the amendment is made.Depending on the airline's policy, some booked fares may not be amended.
// Cancellation Policy:
// Every booking made on Cleartrip is subject to cancellation charges levied by the airline, which may vary by flightand booking class.Some booked fares may be non-refundable per the specific airline's policy.
// Online cancellations:
//  Cancellations can be made online by signing in to your Cleartrip Account. Step by stepdetails for online cancellations are available here
// Offline cancellations:
//  We also accept cancellation requests through phone. However Cleartrip cancellationcharges for such offline cancellations may be higher Cleartrip cancellation charges: Over and above the airline cancellation charges, Cleartrip will levy Rs 300 per passenger per segment for each cancellationOnly cancellation requests made online or telephonic through our customer support shall be entertained.Cleartrip shall not be liable to entertain any cancellation requests made through any other medium including butnot limited to sms, e-mailFor e-tickets, if your cancellation request is made less than 3 hours before departure, you'll need to contact the airline directly to get your reservation cancelled

// Refunds
// It is mandatory to contact Cleartrip for all refunds, as the airline will not be able to refund your tickets booked atcleartrip.com.If you need a refund for paper tickets, please send them back to us. Your tickets must reach us within 48 hours of the time of cancellation so that we can get them endorsed by the airline for you.If your paper ticket gets lost or damaged, the airline will not be able to process a refund request. All cancellations made directly with the Airline need to be intimated to Cleartrip by Email or Phone in order toinitiate the refunds processProcessing times for cancellation and refund requests vary.For complete flight booking terms and conditions click here
